#pragma once
#include "Component.h"
#include "BoxRenderer.h"
#include "Player.h"
#include "Rigidbody.h"
#include "BoxCollider.h"
#include "TextRenderer.h"
#include "Meteor.h"
#include "MeteorSpawner.h"